name: fl_build
description: Build script for Flutter proj.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  json_annotation: ^4.9.0
  build_runner: ^2.4.14
  freezed_annotation: ^3.0.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
  json_serializable: ^6.9.2
  freezed: ^3.0.6
